### ISSUE TITLE
v1.0.0 release broken

### ISSUE THREAD

**Issue by burner-account** [nats-io/nats-account-server#82]
The v1.0.0 release has some issues, some are fixed in master, e.g.
- wrong golang version in Dockerfile `FROM golang:1.12.4 AS builder`, should be >= 1.16, fixed in master
- staticcheck fails (PR approved, but not merged)

This means the **1.0.0** release was never fully tested and since Mar 18 nobody has tried to fire up `make` in CI.

Could you please add some info to the repo release page to tell users to avoid the v1.0.0 release and use master?
And could you please merge #80 soon? 

I am not sure if this 1.0.0 release is as embarrassing as i feel it is or if i am just angry to have wasted my time on this.

**Comment by kozlovic** [comment]
@burner-account Sorry for the unpleasant experience using this repository. I have merged PR #80 and made also some updates to vendor directory, etc.. For sure, this repo does not have the same attention/usage than some other repos such as the NATS Server, etc.. so it is true that probably the code was not up-to-date with latest staticcheck. Maybe we should run a cron job on Travis once a month or something like that.

Keep in mind that staticcheck evolves often and it is possible that some checks are found now that would not have been reported earlier.

Your report is a bit misleading in that the release v1.0.0 (both executable and existing docker image: `docker run natsio/nats-account-server:1.0.0`) is not broken. What I suspect has happened, is that you forked/cloned the repo at v1.0.0 tag and tried to build and/or use staticcheck with versions different than what v1.0.0 was built on back in March of this year?

Regardless, I will sync with some of my colleagues and see if we do another release soon and how to put in place checks so that hopefully does not happen again. Thank you for your understanding.

**Comment by burner-account** [comment]
@kazlovic Thank you very much for your immediate action.
Indeed, i did not use the executable or the pre-built docker image. I followed the instructions from the READ.ME "Building the server" with tag v1.0.0 in order to build a custom docker image that better fits the config/secret injection mechanics of my CI/CD system. 
Please excuse me letting you have a taste of my disappointment.

**Comment by kozlovic** [comment]
@burner-account No worries. I have a PR to add a note in the "building the server" section. I hope this helps: https://github.com/nats-io/nats-account-server/pull/84
